import os, hashlib, json
from pathlib import Path
from solidstate_runtime import InvestigationStartEvidenceGateV4, ExplicitInvestigationProgressionGateV4, SourceBackedInvestigationPathV4, MultiScenarioStatusResolver, ScenarioSelectionInterfaceV1
ROOT=Path(__file__).resolve().parent
SC7=ROOT/'scenario_candidates/scenario7'; EV=SC7/'EXPLORATEUR_PATH_CLOSURE_324.json'; results=[]
def check(name,ok,detail=None): results.append({'name':name,'status':'PASS' if ok else 'FAIL','detail':detail})
ev=json.loads(EV.read_text(encoding='utf-8')); layout=SC7/'source_layout.txt'; lines=layout.read_text(encoding='utf-8').split('\n')
def rh(ref):
    bits=ref.split('_'); a=int(bits[1][1:]); b=int(bits[2][1:]); return hashlib.sha256('\n'.join(lines[a-1:b]).encode()).hexdigest()
def match(r): return [rh(x) for x in r['source_refs']]==r['source_hashes']
check('scenario7_preflight_pass',json.loads((SC7/'SCENARIO7_PREFLIGHT.json').read_text())['status']=='PASS')
struct=json.loads((SC7/'EXPLORATEUR_STRUCTURE_CLASSIFICATION.json').read_text()); check('historical_structure_is_investigation_graph',struct.get('classification')=='INVESTIGATION_GRAPH_CANDIDATE')
roles=json.loads((SC7/'EXPLORATEUR_SOURCE_ROLE_RECOVERY_V1.json').read_text()); check('historical_causal_transition_count_zero_preserved',roles.get('causal_transition_count')==0 and roles.get('pass_real') is False)
topo=json.loads((SC7/'EXPLORATEUR_INVESTIGATION_TOPOLOGY.json').read_text()); check('clue_scene_anchor_count_preserved',len(topo.get('clue_scene_anchors',[]))==107 and all(x.get('causal_edge') is False for x in topo['clue_scene_anchors']))
check('source_layout_sha256_exact',hashlib.sha256(layout.read_bytes()).hexdigest()==ev['source']['source_layout_sha256'])
pdf=Path(os.environ.get('EXPLORATEUR_SOURCE_PDF','')); check('source_pdf_available_and_sha256_exact',pdf.is_file() and hashlib.sha256(pdf.read_bytes()).hexdigest()==ev['source']['pdf_sha256'],str(pdf))
check('start_hash_exact',match(ev['start'])); check('all_transition_hashes_exact',all(match(x) for x in ev['transitions'])); check('start_resolved',InvestigationStartEvidenceGateV4.validate(ev['start']).get('status')=='RESOLVED')
bad=json.loads(json.dumps(ev['start'])); bad['derived_from_clue_anchor']=True; check('clue_anchor_cannot_be_start',InvestigationStartEvidenceGateV4.validate(bad).get('code')=='CLUE_ANCHOR_IS_NOT_START_CAUSALITY')
mat=[ExplicitInvestigationProgressionGateV4.materialize(x) for x in ev['transitions']]; check('all_ten_progression_edges_materialized',len(mat)==10 and all(x.get('status')=='MATERIALIZED' for x in mat))
proof=SourceBackedInvestigationPathV4.prove(ev['start'],ev['transitions'],ev['terminal_scene']); check('complete_source_backed_path_proved',proof.get('status')=='PROVED' and len(proof.get('transition_ids',[]))==10); check('generic_execution_ledger_exact',proof.get('executed_state',{}).get('transition_ledger')==[x['transition_id'] for x in ev['transitions']]); check('no_clue_anchor_edges_used',proof.get('clue_anchor_edges_used')==0 and ev['anti_false_causality']['clue_scene_anchors_promoted_to_edges']==0); check('path_does_not_require_specific_clue_anchor',all(not x.get('requires_specific_clue_anchor') for x in ev['transitions'])); check('path_does_not_self_promote',proof.get('promotion_applied') is False and ev.get('pass_real') is False)
for name,mut,code in [('derived_clue_anchor_fails_closed',{'derived_from_clue_anchor':True},'CLUE_ANCHOR_NOT_CAUSAL_EDGE'),('specific_clue_gate_fails_closed',{'requires_specific_clue_anchor':True},'SPECIFIC_CLUE_ANCHOR_CANNOT_GATE_PATH'),('missing_manual_audit_fails_closed',{'source_language_audit':'UNVERIFIED'},'PROGRESSION_LANGUAGE_AUDIT_MISSING'),('ambiguous_target_fails_closed',{'target_binding_count':2},'PROGRESSION_TARGET_NOT_UNIQUE'),('inferred_transition_fails_closed',{'explicit_source_language':False},'PROGRESSION_SOURCE_NOT_EXPLICIT'),('editorial_reference_fails_closed',{'editorial_reference_only':True},'EDITORIAL_REFERENCE_IS_NOT_PROGRESSION')]:
    r=json.loads(json.dumps(ev['transitions'][3])); r.update(mut); check(name,ExplicitInvestigationProgressionGateV4.validate(r).get('code')==code)
public=SourceBackedInvestigationPathV4.player_safe_summary(proof); check('player_safe_summary_has_no_keeper_evidence',set(public)=={'status','pass_real_candidate','path_length','promotion_applied','clue_anchor_edges_used'})
statuses={k:MultiScenarioStatusResolver.resolve(ROOT/'scenario_candidates',k) for k in ('scenario3','scenario4','scenario5','scenario6','scenario7')}; check('status_boundary_3_to_6_pass_7_blocked',all(statuses[k]['pass_real'] is True for k in ('scenario3','scenario4','scenario5','scenario6')) and statuses['scenario7']['pass_real'] is False)
sel=ScenarioSelectionInterfaceV1(ROOT/'scenario_candidates'); row={x['scenario_key']:x for x in sel.list_scenarios()['scenarios']}['scenario7']; check('scenario7_interface_still_blocked_before_release',row['selectable'] is False and sel.select('scenario7')['status']=='BLOCKED')
passed=sum(x['status']=='PASS' for x in results); report={'schema':'NATIVE_RUNTIME_CHUNK324_REPORT_V1','checkpoint_parent':323,'milestone':'SCENARIO7_SOURCE_BACKED_PATH_CLOSURE_V1','tests_total':len(results),'tests_passed':passed,'tests_failed':len(results)-passed,'status':'PASS' if passed==len(results) else 'FAIL','scenario7_path_status':'PASS_REAL_CANDIDATE' if passed==len(results) else 'BLOCKED','path_length':len(proof.get('transition_ids',[])),'clue_anchor_edges_used':proof.get('clue_anchor_edges_used'),'pass_real_promotion':False,'source_pdf_sha256_expected':ev['source']['pdf_sha256'],'next_gate':'SCENARIO7_PASS_REAL_RELEASE_AUDIT_V1','results':results}
(ROOT/'NATIVE_RUNTIME_CHUNK324_REPORT.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8'); print(json.dumps(report,ensure_ascii=False,indent=2)); raise SystemExit(0 if report['status']=='PASS' else 1)
