import unittest
import lsnt_v17_canonical_graph_candidate as g

class GraphCandidateTests(unittest.TestCase):
    def test_001_identity(self): self.assertEqual(g.SCENARIO_ID, "LSNT-V1.7-STANDALONE-1942")
    def test_002_no_v15_runtime_dependency(self): self.assertFalse(g.GRAPH["runtime_dependency_on_v1_5"])
    def test_003_non_executable_status(self): self.assertFalse(g.graph_candidate_status()["executable"])
    def test_004_hashes_unmaterialized(self): self.assertIsNone(g.CANONICAL_KEEPER_SHA256); self.assertIsNone(g.CANONICAL_PLAYER_SHA256)
    def test_005_launch_1_to_4(self): self.assertEqual(g.GRAPH["launch"]["player_count"], [1,4])
    def test_006_locations(self): self.assertEqual(len(g.GRAPH["locations"]), 10)
    def test_007_clue_nodes(self): self.assertEqual(len(g.GRAPH["clue_network"]), 8)
    def test_008_no_unique_clue(self): self.assertFalse(g.GRAPH["clue_policy"]["single_clue_indispensable"])
    def test_009_three_nonhuman_routes(self): self.assertEqual(g.GRAPH["clue_policy"]["independent_nonhuman_routes"], 3)
    def test_010_world_clock_11(self): self.assertEqual(len(g.GRAPH["world_clock"]), 11)
    def test_011_front_checks(self): self.assertEqual(g.GRAPH["front_track"]["checks"], ["0600","1800"])
    def test_012_front_roll(self): self.assertEqual(g.GRAPH["front_track"]["otherwise_roll"], "1D6")
    def test_013_no_unit_teleport(self): self.assertFalse(g.GRAPH["front_track"]["unit_teleportation"])
    def test_014_travel_7(self): self.assertEqual(len(g.GRAPH["travel"]), 7)
    def test_015_exposure_range(self): self.assertEqual(g.GRAPH["exposure"]["range"], [0,6])
    def test_016_exposure_thresholds(self): self.assertEqual(g.GRAPH["exposure"]["pow_thresholds"], [2,4,6])
    def test_017_no_suspense_stage(self): self.assertTrue(g.GRAPH["exposure"]["suspense_trigger_forbidden"])
    def test_018_sanity_table_6(self): self.assertEqual(len(g.GRAPH["sanity"]), 6)
    def test_019_water_map(self): self.assertEqual(g.GRAPH["shared_resources"]["water_liters_by_player_count"], {1:32,2:48,3:64,4:80})
    def test_020_no_numeric_fuel_invention(self): self.assertIsNone(g.GRAPH["shared_resources"]["fuel_capacity_numeric"]); self.assertIsNone(g.GRAPH["shared_resources"]["fuel_consumption_numeric"])
    def test_021_resolution_methods_6(self): self.assertEqual(len(g.GRAPH["resolution_methods"]), 6)
    def test_022_endings_10(self): self.assertEqual(len(g.GRAPH["endings"]), 10)
    def test_023_single_pc_death_not_end(self): self.assertFalse(g.GRAPH["ending_policy"]["single_pc_death_ends_game"])
    def test_024_romain_not_replacement(self): self.assertFalse(g.GRAPH["ending_policy"]["romain_replacement_pc"])
    def test_025_state_contract(self): self.assertIn("CONSEQUENCES_PENDING", g.GRAPH["state_contract"])
    def test_026_player_projection_no_guardian(self): self.assertFalse(g.player_projection_template(1)["guardian_truth_exposed"])
    def test_027_player_projection_no_future(self): self.assertFalse(g.player_projection_template(1)["future_events_exposed"])
    def test_028_player_projection_no_hashes(self): self.assertFalse(g.player_projection_template(1)["source_hashes_exposed"])
    def test_029_player_projection_no_graph(self): self.assertFalse(g.player_projection_template(1)["canonical_graph_exposed"])
    def test_030_player_count_0_blocked(self): self.assertEqual(g.player_projection_template(0)["status"], "BLOCKED")
    def test_031_player_count_5_blocked(self): self.assertEqual(g.player_projection_template(5)["status"], "BLOCKED")
    def test_032_boolean_count_blocked(self): self.assertEqual(g.player_projection_template(True)["status"], "BLOCKED")
    def test_033_to_036_initial_state_matrix(self):
        for n in range(1,5):
            with self.subTest(n=n):
                s=g.initial_state_candidate(n)
                self.assertEqual(s["status"],"INITIAL_STATE_CANDIDATE_READY_NON_EXECUTABLE")
                self.assertEqual(len(s["characters"]),n)
                self.assertEqual(s["shared_resources"]["water_liters"],{1:32,2:48,3:64,4:80}[n])
                self.assertTrue(s["romain_persy"]["autonomous"])
                self.assertFalse(s["executable"])
    def test_037_separate_knowledge(self):
        s=g.initial_state_candidate(2)
        self.assertIsNot(s["characters"]["PC1"]["knowledge"],s["characters"]["PC2"]["knowledge"])
    def test_038_separate_inventory(self):
        s=g.initial_state_candidate(2)
        self.assertIsNot(s["characters"]["PC1"]["inventory"],s["characters"]["PC2"]["inventory"])
    def test_039_activation_blocked(self): self.assertEqual(g.activate_canonical_graph()["code"],"EXACT_CANONICAL_HASH_ALLOWLIST_UNMATERIALIZED")
    def test_040_activation_zero_mutation(self): self.assertTrue(g.activate_canonical_graph()["zero_mutation"])
    def test_041_v15_hashes_not_canonical(self): self.assertNotIn(g.CANONICAL_KEEPER_SHA256,g.V15_HASHES); self.assertNotIn(g.CANONICAL_PLAYER_SHA256,g.V15_HASHES)
    def test_042_player_known_only(self): self.assertIn("KNOWN_INFORMATION",g.PLAYER_SAFE["interface_fields"])
    def test_043_no_automatic_civil_arm(self): self.assertEqual(g.PLAYER_SAFE["arming_policy"],"NO_AUTOMATIC_CIVIL_ARMING_ROLE_AND_SKILL_REQUIRED")
    def test_044_captured_weapon_must_be_obtained(self): self.assertEqual(g.PLAYER_SAFE["captured_weapon_policy"],"MUST_BE_OBTAINED_IN_PLAY")
    def test_045_time_not_rhythm_adjusted(self): self.assertEqual(g.PLAYER_SAFE["time_policy"],"NO_RHYTHM_ACCELERATION_OR_SLOWDOWN")

if __name__ == '__main__': unittest.main()
